services:

  back:
    image: superknacky/planify_backend:latest
    container_name: Planify-back
    expose:
      - "4000"
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - DATABASE_URL=${DATABASE_URL}
      - FRONTEND_URL=${FRONTEND_URL} # use ',' in .env file for separated list of allowed frontend URLs
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_SECURE=${SMTP_SECURE}
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASS=${SMTP_PASS}
    depends_on:
      - db

  front:
    image: superknacky/planify_frontend:latest
    container_name: Planify-front
    expose:
      - "3000"
    depends_on:
      - back

  db:
    image: postgres:14.15-alpine3.21
    container_name: Planify-postgres
    restart: always
    environment:
      POSTGRES_DB: Librario
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    expose:
      - "5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: Planify-pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: 'False'
    ports:
      - "8080:80"
    depends_on:
      - db

volumes:
  pgdata: